name: smlX
channels: 
- defaults
- conda-forge
dependencies:
- python==3.10.13
- numpy
- pandas
- joblib
- scikit-learn
- seaborn
- dataframe_image
- gradio
- pip
- twofish
- pygrib
- pandasql
- xgboost
- pip
- pip:
  - hopsworks hopsworks>3.7.*
  - modal
